### ISSUE TITLE
Package using conda-forge

### ISSUE THREAD

**Issue by synapticarbors** [markovmodel/PySFD#3]
I just saw the article associated with this package come up in my Google Scholar feed and came to the repo since I was curious about it. It seems like it should be feasible to make `pysfd` available via conda-forge, which might simplify things.

If you do decide to submit a recipe via https://github.com/conda-forge/staged-recipes, please ping me and I'll happily act as a reviewer or help if you get stuck in developing the recipe.

The first step would be to put the package up on pypi, or at a minimum create a release on Github since conda-forge prefers tarballs to repos:

https://conda-forge.org/docs/meta.html#build-from-tarballs-not-repos

**Comment by sstolzenberg** [comment]
Thank you, synapticarbors, will consider conda-forge in the future!
